### PR TITLE
Re-enable reverted changes

### PR DESCRIPTION
**Pull request by jitsedesmet**
This pull request aims to re-enable the reverted changes introduced in #122 . It seemed like the problem was with @rubensworks his dist directory. Some files in that directory where expected to be deleted but weren't. This caused some vague error messaging. This pull request just merges the branch `reverted/jitse`.
I checked:

* Comunica test
* Comunica spec
* Comunica integration
* Sparqlee test
* sparqlee benchmark

This all seemed fine.

I also looked at the 2 commits that where performed on master, and caused merge issues (2224414f2cd1d8afdea5380d70fdf661a8caf7b7, 0170205f6a06c4125138a6730f0ca736f65e874e). The changes performed in these commits are still present in this PR. (Are not changed to the original)

### CODE REVIEW

**Comment by jitsedesmet** [comment]
It seems like some CI tests fail. Is it possible this is a problem with the CI?

**Comment by rubensworks** [comment]
That's a weird error, let me restart it...

**Comment by rubensworks** [comment]
Tests pass now :-)

It's a bit unfortunate that we loose the commit history with this though, as it's all squashed in a single commit.
Any chance you could just do a plain merge and preserve the original 13 commits?

**Comment by jitsedesmet** [comment]
That's indeed a problem. If this is possible within git could you provide some more information? I fear my git knowledge is not that great.

**Comment by rubensworks** [comment]
Should just be a matter of checking out master, creating a new branch from that, and `git merge`-ing `reverted/jitse` into it (which may cause some merge conflicts that can then be resolved via a merge commit).

**Comment by jitsedesmet** [comment]
It is really strange the history wasn't merged as well. I tried again and this time it seems to have worked correctly. I will close this PR in favor of the new one (#125).

**Pull request closed without merging**
