### PR TITLE
Support both upper and lower case operators

### LINKED ISSUE #21: Test support for uppercase and lowercase function names
We should test how our implementation holds up against function names in the algebra that have a different case. I assume it will break hard. Therefore: let's test and potentially fix.

### PR DESCRIPTION
**Pull request by Tpt**
Closes #21

### CODE REVIEW

**Review by rubensworks — COMMENTED** [review]
Would it make sense to also add one (or more?) tests for specific operators testing both uppercase and lowercase invocations?
Such as here: https://github.com/comunica/sparqlee/blob/master/test/integration/functions/op.bnode.test.ts

We could also adapt the `runTestTable` util to execute both variants, but that may be overkill.

**Comment by Tpt** [comment]
> Would it make sense to also add one (or more?) tests for specific operators testing both uppercase and lowercase invocations?

Indeed, I will do so.

**Comment by Tpt** [comment]
> > Would it make sense to also add one (or more?) tests for specific operators testing both uppercase and lowercase invocations?
> 
> Indeed, I will do so.

It's now done.

**Review by rubensworks — APPROVED** [review]
Excellent!

**Pull request merged**
